server:
  port: 9013
spring:
  application:
    name: 9013-rocketmq-consumer
#------------------------------------------------------------------------
#rocketmq配置信息
rocketmq:
  #nameservice服务器地址（多个以英文逗号隔开）
  name-server: CentOS:9876
  #消费者配置
  consumer:
    #组名
    group: consumerA-group
    #监听主题
    topic: syn_tagA
    #tags（监听多个tag时使用 || 进行分割，如果监听所有使用*或者不填）
    tags: syn_tagA||asyn_tagA||oneway_tagA
