server:
  port: 9007

app:
  id: zero10001                      #应用ID

#apollo:
#  cacheDir: /opt/apolloData/                      #配置本地配置缓存目录
##  cluster: default                           #指定使用哪个集群的配置
#  meta: http://121.36.42.17          #DEV环境配置中心地址
#  autoUpdateInjectedSpringProperties: true  #是否开启 Spring 参数自动更新
#  bootstrap:
#    enabled: true                     #是否开启 Apollo
#    namespaces: application             #设置 Namespace
#    eagerLoad:
#      enabled: true
apollo:
  meta: http://106.54.227.205:8080
  bootstrap:
    enabled: true
    namespaces: application


