server:
  port: 7001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=GMT%2B8
    password: 123456
    username: root
  application:
    name: order-service-7001
  profiles:
    active: dev  # 环境设置：dev、test、prod
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatisplus日志  --打印sql语句的日志
  mapper-locations: classpath:com/hfg/mapper/xml/*.xml #配置mapper xml文件的路径
  type-aliases-package: com.hfg.entities   #别名
#logging:  ## 设置日志级别
#  level: info

############## 分页插件PageHelper配置 #############
  #pagehelper.helper-dialect=mysql
  #pagehelper.reasonable=true
  #pagehelper.support-methods-arguments=true
  #pagehelper.pageSizeZero=true
  #pagehelper.params=count=countSql
pagehelper:
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
  params: count=countSql
  helper-dialect: mysql